### ISSUE TITLE
How to launch ipyrest

### ISSUE THREAD

**Issue by humbienri** [deeplook/ipyrest#14]
Silly question I know but how do I use or launch ipyrest? I'm not familiar with Jupyter notebooks so is that where I need to go learn to be able to use ipyrest?

In advance, thank you for your time!

**Comment by deeplook** [comment]
Correct, ipyrest is useful only inside a Jupyter notebook.

**Comment by deeplook** [comment]
I've enabled the discussiobs feature for this kind of requests. If you need more information, maybe let's move there?

**Comment by humbienri** [comment]
Thank you @deeplook. Sorry I just barely saw this. Yeah, I'll go over that way.
